defaults: &defaults
  working_directory: /home/adios2
  steps:
    - checkout:
        path: /home/adios2/source
    - run:
        name: Update
        command: bash source/scripts/circle/runOnCircle.sh update
    - run:
        name: Configure
        command: bash source/scripts/circle/runOnCircle.sh configure
    - run:
        name: Build
        command: bash source/scripts/circle/runOnCircle.sh build
    - run:
        name: Test
        command: |
          ulimit -c unlimited
          export SstVerbose=1
          bash source/scripts/circle/runOnCircle.sh test
    - run:
        command: |
          mkdir -p /tmp/core_dumps
          find . -name '*core*' | xargs bash -c 'for F in $@; do if file -b "$F" | grep -q "core file"; then cp -v --parents "$F" /tmp/core_dumps; fi; done'
        when: on_fail
    - store_artifacts:
        path: /tmp/core_dumps

version: 2

jobs:
  "el7":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:el7

  "el7-gnu7":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:el7-gnu7-ohpc

  "el7-gnu7-openmpi":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:el7-gnu7-openmpi-ohpc

  "el7-intel18":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:el7-intel18-ohpc

  "el7-intel18-impi":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:el7-intel18-impi-ohpc

  "fedora-ubsan":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:fedora-ubsan

  "fedora-mpich-ubsan":
    <<: *defaults
    docker:
      - image: ornladios/adios2-auto:fedora-mpich-ubsan

workflows:
  version: 2
  build:
    jobs:
      - "el7"
      - "el7-gnu7"
      - "el7-gnu7-openmpi"
      - "el7-intel18"
      - "el7-intel18-impi"
      - "fedora-ubsan"
      - "fedora-mpich-ubsan"
