version: 2
jobs:
  build:
    working_directory: /home/adios2/hidecirclesource
    docker:
      - image: ornladios/adios2:el7-ohpc
    steps:
      - checkout
      - run:
          name: Run dashboard scripts
          command: 'cd /home/adios2 && bash hidecirclesource/scripts/circle/runOnCircle.sh'
