#  This file is used to define the GitLab CI/CD pipeline for the ADIOS2 project.
.common-sanitizer:
  variables:
    GITLAB_SITE: "UO CI (gitlab.spack.io)"
    CI_BIN_DIR:  "$CI_PROJECT_DIR/build"
  tags:
    - medium
    - uo
    - public
    - x86_64
  interruptible: true

.common-build:
  extends:
    - .common-sanitizer
  stage: build
  script:
    - bash scripts/ci/gitlab-ci/run.sh update
    - bash scripts/ci/gitlab-ci/run.sh configure
    - bash scripts/ci/gitlab-ci/run.sh build
  artifacts:
    expire_in: 1 hours
    when: always
    paths:
      - $CI_BIN_DIR/bin/
      - $CI_BIN_DIR/lib/
      - $CI_BIN_DIR/lib64/
      - $CI_BIN_DIR/thirdparty/**/lib64/
      - $CI_BIN_DIR/testing/
      - $CI_BIN_DIR/source/**/*.h
      - $CI_BIN_DIR/source/**/*.in

      # CTest and CMake install files.
      - $CI_BIN_DIR/CMakeCache.txt
      - $CI_BIN_DIR/**/*.cmake
      - $CI_BIN_DIR/Testing/

      # CDash files.
      - $CI_BIN_DIR/DartConfiguration.tcl

.common-test:
  extends:
    - .common-sanitizer
  stage: test
  script:
    - bash scripts/ci/gitlab-ci/run.sh memcheck

#===============================================================================

build:uo-sanitizer-asan:
  image: ornladios/adios2:ci-fedora-asan
  extends: [.common-build]

build:uo-sanitizer-msan:
  image: ornladios/adios2:ci-fedora-msan
  extends: [.common-build]

build:uo-sanitizer-tsan:
  image: ornladios/adios2:ci-fedora-tsan
  extends: [.common-build]

build:uo-sanitizer-ubsan:
  image: ornladios/adios2:ci-fedora-ubsan
  extends: [.common-build]

test:uo-sanitizer-asan:
  image: ornladios/adios2:ci-fedora-asan
  extends: [.common-test]
  needs: [build:uo-sanitizer-asan]

test:uo-sanitizer-msan:
  image: ornladios/adios2:ci-fedora-msan
  extends: [.common-test]
  needs: [build:uo-sanitizer-msan]

test:uo-sanitizer-tsan:
  image: ornladios/adios2:ci-fedora-tsan
  extends: [.common-test]
  needs: [build:uo-sanitizer-tsan]

test:uo-sanitizer-ubsan:
  image: ornladios/adios2:ci-fedora-ubsan
  extends: [.common-test]
  needs: [build:uo-sanitizer-ubsan]
