---
# adios2 config.yaml prototype

- io:
  name: "SimulationOutput"
  engine:
    Type: "BP4"
    CollectiveMetadata: On
    Threads: 2
    InitialBufferSize: 10Gb

- io: 
  name: "PDFAnalysisOutput"
  engine:
    type: "BP4"
    # Simple parameters are passed as dict/maps as in adios2 code
    # SST engine parameters
    RendevouzReaderCount: 1
    QueueLimit: 5
    QueueFullPolicy: Block
    # BP4/SST engine parameters
    OpenTimeOutSecs: 10.0
    MaxBufferSize: 100Gb
    #CollectiveMetadata: On  # easily commented out
  
  variables:
  
    - name: "U"
      operations:
        - type: sz
          accuracy: 0.001
   
    - name: "V"
      operations:
        - {type: sz, accuracy: 0.001}
        - {type: z-checker, key1: value1, key2: value2}
  
  transports:
    - {type: file, library: fstream}
    - {type: rdma, library: ibverbs} 
    