name: Docker

on: 
  push: 
    branches: 
    - master 
    - release* 
  pull_request: 
    branches: 
    - master 
    - release* 

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseos: [
          ubuntu18.04,
          ubuntu20.04 ]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build image
      run: |
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]
          then
              adios_ver="pr$(expr "${GITHUB_REF}" : 'refs/pull/\([^/]*\)')"
          else
              adios_ver="${GITHUB_REF##refs/heads/}"
          fi
          echo "adios_ver=${adios_ver}"
          docker build \
              -t ornladios/adios2:${adios_ver}-${{ matrix.baseos }} \
              --build-arg adios_ver=${adios_ver} \
              --build-arg base=${{ matrix.baseos }} \
              scripts/docker/complete
    - name: Push image to Docker Hub
      if: github.event_name == 'push'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
          docker login \
              --username="${DOCKERHUB_USERNAME}" \
              --password="${DOCKERHUB_PASSWORD}" && \
          docker push \
              ornladios/adios2:${GITHUB_REF##refs/heads/}-${{ matrix.baseos }}
