name: Sync jobs

on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  sync-script-ornl:
    if: github.repository == 'ornladios/ADIOS2'
    name: ORNL sync
    runs-on: ubuntu-20.04
    environment: sync-script
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6.15'
      - run: pip install python-dateutil PyGithub
      - run: >
          .gitlab/config/SpackCIBridge.py
          ornladios/ADIOS2
          git@code.ornl.gov:ecpcitest/adios2.git
          https://code.ornl.gov/
          ecpcitest/adios2
          --prereq-check=format
          --prereq-check=git_checks
          --disable-status-post
        env:
          GITLAB_SSH_KEY_BASE64: ${{ secrets.GITLAB_SSH_KEY_BASE64}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sync-script-spack:
    if: github.repository == 'ornladios/ADIOS2'
    name: Spack sync
    runs-on: ubuntu-20.04
    environment: sync-script
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6.15'
      - run: pip install python-dateutil PyGithub
      - run: >
          .gitlab/config/SpackCIBridge.py
          ornladios/ADIOS2
          git@ssh.gitlab.spack.io:adios2/adios2.git
          https://gitlab.spack.io/
          adios2/ADIOS2
          --prereq-check=format
          --prereq-check=git_checks
          --status-context="Frank CI (sanitizers)"
          || true
        env:
          GITLAB_SSH_KEY_BASE64: ${{ secrets.GITLAB_SPACK_SSH_KEY_BASE64}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

